// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QueryKit.WebApiTestProject.Database;

#nullable disable

namespace QueryKit.WebApiTestProject.Migrations
{
    [DbContext(typeof(TestingDbContext))]
    partial class TestingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Authors.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_author");

                    b.HasIndex("RecipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_author_recipe_id");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Ingredients.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measure");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_ingredient");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_ingredient_recipe_id");

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateOfOrigin")
                        .HasColumnType("date")
                        .HasColumnName("date_of_origin");

                    b.Property<string>("Directions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directions");

                    b.Property<bool>("HaveMadeItMyself")
                        .HasColumnType("boolean")
                        .HasColumnName("have_made_it_myself");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.TestingPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("BirthMonth")
                        .HasColumnType("text")
                        .HasColumnName("birth_month");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("Favorite")
                        .HasColumnType("boolean")
                        .HasColumnName("favorite");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset?>("SpecificDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("specific_date");

                    b.Property<DateTime>("SpecificDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("specific_date_time");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Authors.Author", b =>
                {
                    b.HasOne("QueryKit.WebApiTestProject.Entities.Recipes.Recipe", "Recipe")
                        .WithOne("Author")
                        .HasForeignKey("QueryKit.WebApiTestProject.Entities.Authors.Author", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Ingredients.Ingredient", b =>
                {
                    b.HasOne("QueryKit.WebApiTestProject.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.TestingPerson", b =>
                {
                    b.OwnsOne("QueryKit.WebApiTestProject.Entities.Address", "PhysicalAddress", b1 =>
                        {
                            b1.Property<Guid>("TestingPersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_line1");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("physical_address_state");

                            b1.HasKey("TestingPersonId");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("TestingPersonId")
                                .HasConstraintName("fk_people_people_id");
                        });

                    b.Navigation("PhysicalAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("QueryKit.WebApiTestProject.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
